services:
  db:
    image: postgres:16-alpine
    container_name: audio_system_db
    environment:
      POSTGRES_DB: audio_db
      POSTGRES_USER: audio_user
      POSTGRES_PASSWORD: audio_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audio_user -d audio_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
